[project]
name = "currens"
version = "0.1.0"
description = "Collection of tools for working with currency data"
readme = "README.md"
requires-python = ">=3.13"
dependencies =  [
    "sqlalchemy",
    "pandas",
    "requests",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.2",
]
